export const testimonials = [
  {
    company: "Zoomerr",
    logo: "⚡",
    text: "Non risus viverra enim, quis. Eget vitae arcu vivamus sit tellus, viverra turpis lorem. Varius a turpis urna id porttitor.",
    author: "Hellen Jummy",
    role: "Team Lead",
    avatar: "src/assets/sneaker-cover-1.jpg",
  },
  {
    company: "SHELLS",
    logo: "🎯",
    text: "Aliquet ridiculus mi porta habitant vulputate rhoncus, mattis amet enim. Sit purus venenatis velit semper lectus sed ornare quam nulla.",
    author: "Hellena John",
    role: "Co-founder",
    avatar: "src/assets/sneaker-cover-1.jpg",
  },
  {
    company: "ArtVenue",
    logo: "🎨",
    text: "A eget sed posuere dui risus habitasse mauris. Venenatis aliquet id ultrices a lacus. Pretium vehicula pretium posuere justo sed.",
    author: "David Oshodi",
    role: "Manager",
    avatar: "src/assets/sneaker-cover-1.jpg",
  },
  {
    company: "WATTPAD",
    logo: "📚",
    text: "Magna eget tristique parturient integer sed ipsum et quis amet. Ut urna ornare ante mauris, varius nisl potenti bibendum.",
    author: "Charolette Hanlin",
    role: "CEO",
    avatar: "src/assets/sneaker-cover-1.jpg",
  },
  {
    company: "Zoomerr",
    logo: "⚡",
    text: "Non risus viverra enim, quis. Eget vitae arcu vivamus sit tellus, viverra turpis lorem. Varius a turpis urna id porttitor.",
    author: "Hellen Jummy",
    role: "Team Lead",
    avatar: "src/assets/sneaker-cover-1.jpg",
  },
  {
    company: "SHELLS",
    logo: "🎯",
    text: "Aliquet ridiculus mi porta habitant vulputate rhoncus, mattis amet enim. Sit purus venenatis velit semper lectus sed ornare quam nulla.",
    author: "Hellena John",
    role: "Co-founder",
    avatar: "src/assets/sneaker-cover-1.jpg",
  },
  {
    company: "ArtVenue",
    logo: "🎨",
    text: "A eget sed posuere dui risus habitasse mauris. Venenatis aliquet id ultrices a lacus. Pretium vehicula pretium posuere justo sed.",
    author: "David Oshodi",
    role: "Manager",
    avatar: "src/assets/sneaker-cover-1.jpg",
  },
  {
    company: "WATTPAD",
    logo: "📚",
    text: "Magna eget tristique parturient integer sed ipsum et quis amet. Ut urna ornare ante mauris, varius nisl potenti bibendum.",
    author: "Charolette Hanlin",
    role: "CEO",
    avatar: "src/assets/sneaker-cover-1.jpg",
  },
];